name: Create Pull Request on Direct Push to Main

on:
  push:
    branches:
      - main

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get the commit message and committer username
        id: commit
        run: |
          COMMIT_MESSAGE=$(git log --format=%B -n 1 ${{ github.sha }})
          COMMITTER_USERNAME=$(git log --format=%an -n 1 ${{ github.sha }})
          echo "::set-output name=message::[${COMMITTER_USERNAME}] ${COMMIT_MESSAGE}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: ${{ github.ref }}
          title: ${{ steps.commit.outputs.message }}
          body: |
            This is an automatically created Pull Request.
            It was triggered by a direct push to the main branch.

