name: Create Pull Request on Commit Keywords

on:
  push:
    branches:
      - '*'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get commit message
        id: commit
        run: echo "::set-output name=message::$(git log --format=%B -n 1 ${{ github.sha }})"

      - name: Check commit message keywords
        id: check-keywords
        run: |
          COMMIT_MESSAGE=$(echo "${{ steps.commit.outputs.message }}")
          if [[ $COMMIT_MESSAGE =~ ^(feat|fix|docs|chore|style|test) ]]; then
            echo "::set-output name=keywords::true"
          else
            echo "::set-output name=keywords::false"
          fi

      - name: Create Pull Request
        if: steps.check-keywords.outputs.keywords == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: ${{ github.ref }}
          title: ${{ github.actor }} - ${{ steps.commit.outputs.message }}
          body: |
            This is an automatically created Pull Request.
            It was triggered by a push to the branch ${{ github.ref }}.

